# Generated by Django 4.0.1 on 2022-01-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, upload_to='media/uploads/avatars/'),
        ),
    ]
