# Generated by Django 4.0.1 on 2022-01-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_avatar',
            new_name='profile_pic',
        ),
    ]
