# Generated by Django 4.0.1 on 2022-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='323092302', max_length=255, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
    ]
