# Generated by Django 4.0.1 on 2022-01-08 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('amount_per_our', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('place', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'other')], max_length=255)),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
