# Generated by Django 4.0.1 on 2022-01-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorfeature',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
