# Generated by Django 4.0.1 on 2022-01-08 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_rename_doctorspecializations_doctorspecialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHour',
            fields=[
                ('monday', models.CharField(blank=True, default='07:00 AM - 09:00 PM', max_length=255)),
                ('tuesday', models.CharField(blank=True, default='07:00 AM - 09:00 PM', max_length=255)),
                ('wednesday', models.CharField(blank=True, default='07:00 AM - 09:00 PM', max_length=255)),
                ('thursday', models.CharField(blank=True, default='07:00 AM - 09:00 PM', max_length=255)),
                ('friday', models.CharField(blank=True, default='07:00 AM - 09:00 PM', max_length=255)),
                ('saturday', models.CharField(blank=True, default='07:00 AM - 09:00 PM', max_length=255)),
                ('sunday', models.CharField(blank=True, max_length=255)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='doctors.doctor')),
            ],
        ),
    ]
