# Generated by Django 4.0.1 on 2022-01-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
    ]
